CREATE TABLE IF NOT EXISTS registration_requests (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  roster_entry_id BIGINT UNSIGNED NOT NULL,
  group_id BIGINT UNSIGNED NOT NULL,
  canonical_name VARCHAR(128) NOT NULL,
  username VARCHAR(64) NOT NULL,
  email_normalized VARCHAR(255) NULL,
  password_hash VARCHAR(255) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'pending',
  rejection_reason VARCHAR(255) NOT NULL DEFAULT '',
  reviewed_by BIGINT UNSIGNED NULL,
  reviewed_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  pending_roster_entry_id BIGINT UNSIGNED GENERATED ALWAYS AS (CASE WHEN status='pending' THEN roster_entry_id ELSE NULL END) STORED,
  pending_username VARCHAR(64) GENERATED ALWAYS AS (CASE WHEN status='pending' THEN LOWER(username) ELSE NULL END) STORED,
  pending_email VARCHAR(255) GENERATED ALWAYS AS (CASE WHEN status='pending' THEN email_normalized ELSE NULL END) STORED,
  UNIQUE KEY uk_registration_pending_roster (pending_roster_entry_id),
  UNIQUE KEY uk_registration_pending_username (pending_username),
  UNIQUE KEY uk_registration_pending_email (pending_email),
  KEY idx_registration_group_status_created (group_id, status, created_at),
  KEY idx_registration_roster_status (roster_entry_id, status),
  KEY idx_registration_username_status (username, status),
  KEY idx_registration_email_status (email_normalized, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
