import { defineStore } from 'pinia';

export const useAppStateStore = defineStore('appState', {
  state: () => ({
    booted: false,
    networkBusy: false,
    online: typeof navigator === 'undefined' ? true : navigator.onLine,
    authenticated: false,
    user: null,
    tab: 'home',
    adminSection: 'overview',
    sidebarCollapsed: false,
    pageTitle: 'AGP',
    navItems: [],
    groups: [],
    currentGroupID: 0,
    defaultGroupID: 0,
    showGroupPicker: false,
    toast: '',
    resources: [],
    publicLibrary: [],
    resourceLoading: false,
    members: [],
    canAdmin: false,
    canEditLearning: false,
    adminLoading: false,
    learningConfig: {},
    weekDraft: null,
    weeks: [],
    resourceLibrary: [],
    calendar: null,
  }),
  actions: {
    setSnapshot(snapshot) {
      Object.assign(this, {
        booted: Boolean(snapshot?.booted),
        networkBusy: Boolean(snapshot?.networkBusy),
        online: snapshot?.online !== false,
        authenticated: Boolean(snapshot?.authenticated),
        user: snapshot?.user || null,
        tab: snapshot?.tab || 'home',
        adminSection: snapshot?.adminSection || 'overview',
        sidebarCollapsed: Boolean(snapshot?.sidebarCollapsed),
        pageTitle: snapshot?.pageTitle || 'AGP',
        navItems: Array.isArray(snapshot?.navItems) ? snapshot.navItems : [],
        groups: Array.isArray(snapshot?.groups) ? snapshot.groups : [],
        currentGroupID: Number(snapshot?.currentGroupID || 0),
        defaultGroupID: Number(snapshot?.defaultGroupID || 0),
        showGroupPicker: Boolean(snapshot?.showGroupPicker),
        toast: snapshot?.toast || '',
        resources: Array.isArray(snapshot?.resources) ? snapshot.resources : [],
        publicLibrary: Array.isArray(snapshot?.publicLibrary) ? snapshot.publicLibrary : [],
        resourceLoading: Boolean(snapshot?.resourceLoading),
        members: Array.isArray(snapshot?.members) ? snapshot.members : [],
        canAdmin: Boolean(snapshot?.canAdmin),
        canEditLearning: Boolean(snapshot?.canEditLearning),
        adminLoading: Boolean(snapshot?.adminLoading),
        learningConfig: snapshot?.learningConfig || {},
        weekDraft: snapshot?.weekDraft || null,
        weeks: Array.isArray(snapshot?.weeks) ? snapshot.weeks : [],
        resourceLibrary: Array.isArray(snapshot?.resourceLibrary) ? snapshot.resourceLibrary : [],
        calendar: snapshot?.calendar || null,
      });
    },
  },
});
